#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d spice-vdagent remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.4.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'spice-vdagentd.service' 'spice-vdagentd.socket' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'spice-vdagentd.service' 'spice-vdagentd.socket' >/dev/null || true
		deb-systemd-helper unmask 'spice-vdagentd.service' 'spice-vdagentd.socket' >/dev/null || true
	fi
fi
# End automatically added section
