#! /bin/sh

set -e

case "$1" in
    configure)

        addgroup --system --quiet sunxi-fel
        if which udevadm >/dev/null 2>&1; then
            udevadm trigger --subsystem-match usb --attr-match=idVendor=1f3a --attr-match=idProduct=efe8 || true
        fi

        ;;

    abort-upgrade|abort-remove|abort-deconfigure)

        ;;

    *)

        echo "postinst called with unknown argument \`$1'" >&2
        exit 0

        ;;
esac



exit 0
