#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/sysfsutils" ]; then
		update-rc.d sysfsutils start 20 2 3 4 5 . >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d sysfsutils $_dh_action || exit 1
	fi
fi
# End automatically added section
