#ifndef ATL_INSTINFO_H
   #define ATL_INSTINFO_H

#define ATL_ARCH "GENERIC64"
#define ATL_INSTFLAGS "-1 0 -a 1 -l 1"
#define ATL_F2CDEFS "-DAdd_ -DF77_INTEGER=int -DStringSunStyle"
#define ATL_ARCHDEFS "-DATL_OS_Linux -DATL_ARCH_GENERIC -DATL_USE64BITS -DATL_GAS_ARM64"
#define ATL_DKCFLAGS "-Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/atlas-EDJcXf/atlas-3.10.3=. -fstack-protector-strong -fPIC"
#define ATL_DKC "/usr/bin/gcc"
#define ATL_SKCFLAGS "-Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/atlas-EDJcXf/atlas-3.10.3=. -fstack-protector-strong -fPIC"
#define ATL_SKC "/usr/bin/gcc"
#define ATL_DMCFLAGS "-Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/atlas-EDJcXf/atlas-3.10.3=. -fstack-protector-strong -fPIC"
#define ATL_DMC "/usr/bin/gcc"
#define ATL_SMCFLAGS "-Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/atlas-EDJcXf/atlas-3.10.3=. -fstack-protector-strong -fPIC"
#define ATL_SMC "/usr/bin/gcc"
#define ATL_ICCFLAGS "-DL2SIZE=33554432 -I/build/atlas-EDJcXf/atlas-3.10.3/build/include -I/build/atlas-EDJcXf/atlas-3.10.3/build/..//include -I/build/atlas-EDJcXf/atlas-3.10.3/build/..//include/contrib -DAdd_ -DF77_INTEGER=int -DStringSunStyle -DATL_OS_Linux -DATL_ARCH_GENERIC -DATL_USE64BITS -DATL_GAS_ARM64 -DATL_DYLIBS -DWALL -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/atlas-EDJcXf/atlas-3.10.3=. -fstack-protector-strong -fPIC"
#define ATL_ICC "/usr/bin/gcc"
#define ATL_F77FLAGS "-g -O2 -fdebug-prefix-map=/build/atlas-EDJcXf/atlas-3.10.3=. -fstack-protector-strong -fPIC"
#define ATL_F77 "/usr/bin/gfortran"
#define ATL_DKCVERS "gcc (Debian 8.2.0-14) 8.2.0"
#define ATL_SKCVERS "gcc (Debian 8.2.0-14) 8.2.0"
#define ATL_DMCVERS "gcc (Debian 8.2.0-14) 8.2.0"
#define ATL_SMCVERS "gcc (Debian 8.2.0-14) 8.2.0"
#define ATL_ICCVERS "gcc (Debian 8.2.0-14) 8.2.0"
#define ATL_F77VERS "GNU Fortran (Debian 8.2.0-14) 8.2.0"
#define ATL_SYSINFO "Linux arm-arm-04 4.9.0-8-arm64 #1 SMP Debian 4.9.130-2 (2018-10-27) aarch64 GNU/Linux"
#define ATL_DATE    "Tue Jan 22 12:02:08 UTC 2019"
#define ATL_UNAM    "buildd"
#define ATL_VERS    "3.10.3"

#endif
